apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-spring-boot-app
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing  # Expose ALB to the public internet
    alb.ingress.kubernetes.io/actions.redirect-to-https: >
      {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}
    alb.ingress.kubernetes.io/group.name: shared-group  

spec:
  ingressClassName: alb
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redirect-to-https
            port:
              name: use-annotation

  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: spring-boot-app-svc
            port: 
              number: 80
      - path: /live
        pathType: Exact
        backend:
          service:
            name: spring-boot-app-svc
            port: 
              number: 80


 