# This is a basic workflow to help you get started with Actions

name: arc_image_push

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (optional for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub using credentials stored in GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{secrets.DOCKER_USERNAME}} 
            password: ${{secrets.DOCKER_PASSWORD}}  # Using Access Token as the password
            
      # Step 4: Build the Docker image using the specified Dockerfile
      - name: Build Docker image
        run: |
           docker build -f Custom_ACR_Image_DockerFile -t mosama25/Custom_ARC_Image:latest .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image 
        run: |
              docker push mosama25/Custom_ARC_Image:latest
