name: Terraform Deployment

on:

  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action (apply/destroy)'
        required: true
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: "Terraform ${{ github.event.inputs.action  }}"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: Terraform


      - name: Terraform Apply
        if: github.event.inputs.action == 'apply' || github.event_name == 'push'
        run: terraform apply --auto-approve 
        env:
          TF_VAR_TXT_OWNER_ID: ${{ secrets.TXT_OWNER_ID }}
          TF_VAR_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        working-directory: Terraform  

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: |
          aws eks update-kubeconfig --region us-east-1 --name eks-cluster
          kubectl delete ingress --all --all-namespaces
          terraform destroy --auto-approve
        env:
          TF_VAR_TXT_OWNER_ID: ${{ secrets.TXT_OWNER_ID }}
          TF_VAR_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        working-directory: Terraform  
